// CountriesWithFlags.tsx
export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const countries: Country[] = [
  { name: "Nigeria", code: "NG", flag: "https://flagcdn.com/w320/ng.png" },

  {
    name: "United States of America",
    code: "US",
    flag: "https://flagcdn.com/w320/us.png",
  },
  { name: "Afghanistan", code: "AF", flag: "https://flagcdn.com/w320/af.png" },
  { name: "Albania", code: "AL", flag: "https://flagcdn.com/w320/al.png" },
  { name: "Algeria", code: "DZ", flag: "https://flagcdn.com/w320/dz.png" },
  { name: "Andorra", code: "AD", flag: "https://flagcdn.com/w320/ad.png" },
  { name: "Angola", code: "AO", flag: "https://flagcdn.com/w320/ao.png" },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    flag: "https://flagcdn.com/w320/ag.png",
  },
  { name: "Argentina", code: "AR", flag: "https://flagcdn.com/w320/ar.png" },
  { name: "Armenia", code: "AM", flag: "https://flagcdn.com/w320/am.png" },
  { name: "Australia", code: "AU", flag: "https://flagcdn.com/w320/au.png" },
  { name: "Austria", code: "AT", flag: "https://flagcdn.com/w320/at.png" },
  { name: "Azerbaijan", code: "AZ", flag: "https://flagcdn.com/w320/az.png" },
  { name: "Bahamas", code: "BS", flag: "https://flagcdn.com/w320/bs.png" },
  { name: "Bahrain", code: "BH", flag: "https://flagcdn.com/w320/bh.png" },
  { name: "Bangladesh", code: "BD", flag: "https://flagcdn.com/w320/bd.png" },
  { name: "Barbados", code: "BB", flag: "https://flagcdn.com/w320/bb.png" },
  { name: "Belarus", code: "BY", flag: "https://flagcdn.com/w320/by.png" },
  { name: "Belgium", code: "BE", flag: "https://flagcdn.com/w320/be.png" },
  { name: "Belize", code: "BZ", flag: "https://flagcdn.com/w320/bz.png" },
  { name: "Benin", code: "BJ", flag: "https://flagcdn.com/w320/bj.png" },
  { name: "Bhutan", code: "BT", flag: "https://flagcdn.com/w320/bt.png" },
  { name: "Bolivia", code: "BO", flag: "https://flagcdn.com/w320/bo.png" },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    flag: "https://flagcdn.com/w320/ba.png",
  },
  { name: "Botswana", code: "BW", flag: "https://flagcdn.com/w320/bw.png" },
  { name: "Brazil", code: "BR", flag: "https://flagcdn.com/w320/br.png" },
  { name: "Brunei", code: "BN", flag: "https://flagcdn.com/w320/bn.png" },
  { name: "Bulgaria", code: "BG", flag: "https://flagcdn.com/w320/bg.png" },
  { name: "Burkina Faso", code: "BF", flag: "https://flagcdn.com/w320/bf.png" },
  { name: "Burundi", code: "BI", flag: "https://flagcdn.com/w320/bi.png" },
  { name: "Cabo Verde", code: "CV", flag: "https://flagcdn.com/w320/cv.png" },
  { name: "Cambodia", code: "KH", flag: "https://flagcdn.com/w320/kh.png" },
  { name: "Cameroon", code: "CM", flag: "https://flagcdn.com/w320/cm.png" },
  { name: "Canada", code: "CA", flag: "https://flagcdn.com/w320/ca.png" },
  {
    name: "Central African Republic",
    code: "CF",
    flag: "https://flagcdn.com/w320/cf.png",
  },
  { name: "Chad", code: "TD", flag: "https://flagcdn.com/w320/td.png" },
  { name: "Chile", code: "CL", flag: "https://flagcdn.com/w320/cl.png" },
  { name: "China", code: "CN", flag: "https://flagcdn.com/w320/cn.png" },
  { name: "Colombia", code: "CO", flag: "https://flagcdn.com/w320/co.png" },
  { name: "Comoros", code: "KM", flag: "https://flagcdn.com/w320/km.png" },
  {
    name: "Congo (Congo-Brazzaville)",
    code: "CG",
    flag: "https://flagcdn.com/w320/cg.png",
  },
  { name: "Costa Rica", code: "CR", flag: "https://flagcdn.com/w320/cr.png" },
  { name: "Croatia", code: "HR", flag: "https://flagcdn.com/w320/hr.png" },
  { name: "Cuba", code: "CU", flag: "https://flagcdn.com/w320/cu.png" },
  { name: "Cyprus", code: "CY", flag: "https://flagcdn.com/w320/cy.png" },
  {
    name: "Czechia (Czech Republic)",
    code: "CZ",
    flag: "https://flagcdn.com/w320/cz.png",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    flag: "https://flagcdn.com/w320/cd.png",
  },
  { name: "Denmark", code: "DK", flag: "https://flagcdn.com/w320/dk.png" },
  { name: "Djibouti", code: "DJ", flag: "https://flagcdn.com/w320/dj.png" },
  { name: "Dominica", code: "DM", flag: "https://flagcdn.com/w320/dm.png" },
  {
    name: "Dominican Republic",
    code: "DO",
    flag: "https://flagcdn.com/w320/do.png",
  },
  { name: "Ecuador", code: "EC", flag: "https://flagcdn.com/w320/ec.png" },
  { name: "Egypt", code: "EG", flag: "https://flagcdn.com/w320/eg.png" },
  { name: "El Salvador", code: "SV", flag: "https://flagcdn.com/w320/sv.png" },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    flag: "https://flagcdn.com/w320/gq.png",
  },
  { name: "Eritrea", code: "ER", flag: "https://flagcdn.com/w320/er.png" },
  { name: "Estonia", code: "EE", flag: "https://flagcdn.com/w320/ee.png" },
  {
    name: "Eswatini (fmr. Swaziland)",
    code: "SZ",
    flag: "https://flagcdn.com/w320/sz.png",
  },
  { name: "Ethiopia", code: "ET", flag: "https://flagcdn.com/w320/et.png" },
  { name: "Fiji", code: "FJ", flag: "https://flagcdn.com/w320/fj.png" },
  { name: "Finland", code: "FI", flag: "https://flagcdn.com/w320/fi.png" },
  { name: "France", code: "FR", flag: "https://flagcdn.com/w320/fr.png" },
  { name: "Gabon", code: "GA", flag: "https://flagcdn.com/w320/ga.png" },
  { name: "Gambia", code: "GM", flag: "https://flagcdn.com/w320/gm.png" },
  { name: "Georgia", code: "GE", flag: "https://flagcdn.com/w320/ge.png" },
  { name: "Germany", code: "DE", flag: "https://flagcdn.com/w320/de.png" },
  { name: "Ghana", code: "GH", flag: "https://flagcdn.com/w320/gh.png" },
  { name: "Greece", code: "GR", flag: "https://flagcdn.com/w320/gr.png" },
  { name: "Grenada", code: "GD", flag: "https://flagcdn.com/w320/gd.png" },
  { name: "Guatemala", code: "GT", flag: "https://flagcdn.com/w320/gt.png" },
  { name: "Guinea", code: "GN", flag: "https://flagcdn.com/w320/gn.png" },
  {
    name: "Guinea-Bissau",
    code: "GW",
    flag: "https://flagcdn.com/w320/gw.png",
  },
  { name: "Guyana", code: "GY", flag: "https://flagcdn.com/w320/gy.png" },
  { name: "Haiti", code: "HT", flag: "https://flagcdn.com/w320/ht.png" },
  { name: "Honduras", code: "HN", flag: "https://flagcdn.com/w320/hn.png" },
  { name: "Hungary", code: "HU", flag: "https://flagcdn.com/w320/hu.png" },
  { name: "Iceland", code: "IS", flag: "https://flagcdn.com/w320/is.png" },
  { name: "India", code: "IN", flag: "https://flagcdn.com/w320/in.png" },
  { name: "Indonesia", code: "ID", flag: "https://flagcdn.com/w320/id.png" },
  { name: "Iran", code: "IR", flag: "https://flagcdn.com/w320/ir.png" },
  { name: "Iraq", code: "IQ", flag: "https://flagcdn.com/w320/iq.png" },
  { name: "Ireland", code: "IE", flag: "https://flagcdn.com/w320/ie.png" },
  { name: "Israel", code: "IL", flag: "https://flagcdn.com/w320/il.png" },
  { name: "Italy", code: "IT", flag: "https://flagcdn.com/w320/it.png" },
  { name: "Jamaica", code: "JM", flag: "https://flagcdn.com/w320/jm.png" },
  { name: "Japan", code: "JP", flag: "https://flagcdn.com/w320/jp.png" },
  { name: "Jordan", code: "JO", flag: "https://flagcdn.com/w320/jo.png" },
  { name: "Kazakhstan", code: "KZ", flag: "https://flagcdn.com/w320/kz.png" },
  { name: "Kenya", code: "KE", flag: "https://flagcdn.com/w320/ke.png" },
  { name: "Kiribati", code: "KI", flag: "https://flagcdn.com/w320/ki.png" },
  {
    name: "Korea (North)",
    code: "KP",
    flag: "https://flagcdn.com/w320/kp.png",
  },
  {
    name: "Korea (South)",
    code: "KR",
    flag: "https://flagcdn.com/w320/kr.png",
  },
  { name: "Kosovo", code: "XK", flag: "https://flagcdn.com/w320/xk.png" },
  { name: "Kuwait", code: "KW", flag: "https://flagcdn.com/w320/kw.png" },
  { name: "Kyrgyzstan", code: "KG", flag: "https://flagcdn.com/w320/kg.png" },
  { name: "Laos", code: "LA", flag: "https://flagcdn.com/w320/la.png" },
  { name: "Latvia", code: "LV", flag: "https://flagcdn.com/w320/lv.png" },
  { name: "Lebanon", code: "LB", flag: "https://flagcdn.com/w320/lb.png" },
  { name: "Lesotho", code: "LS", flag: "https://flagcdn.com/w320/ls.png" },
  { name: "Liberia", code: "LR", flag: "https://flagcdn.com/w320/lr.png" },
  { name: "Libya", code: "LY", flag: "https://flagcdn.com/w320/ly.png" },
  {
    name: "Liechtenstein",
    code: "LI",
    flag: "https://flagcdn.com/w320/li.png",
  },
  { name: "Lithuania", code: "LT", flag: "https://flagcdn.com/w320/lt.png" },
  { name: "Luxembourg", code: "LU", flag: "https://flagcdn.com/w320/lu.png" },
  { name: "Madagascar", code: "MG", flag: "https://flagcdn.com/w320/mg.png" },
  { name: "Malawi", code: "MW", flag: "https://flagcdn.com/w320/mw.png" },
  { name: "Malaysia", code: "MY", flag: "https://flagcdn.com/w320/my.png" },
  { name: "Maldives", code: "MV", flag: "https://flagcdn.com/w320/mv.png" },
  { name: "Mali", code: "ML", flag: "https://flagcdn.com/w320/ml.png" },
  { name: "Malta", code: "MT", flag: "https://flagcdn.com/w320/mt.png" },
  {
    name: "Marshall Islands",
    code: "MH",
    flag: "https://flagcdn.com/w320/mh.png",
  },
  { name: "Mauritania", code: "MR", flag: "https://flagcdn.com/w320/mr.png" },
  { name: "Mauritius", code: "MU", flag: "https://flagcdn.com/w320/mu.png" },
  { name: "Mexico", code: "MX", flag: "https://flagcdn.com/w320/mx.png" },
  { name: "Micronesia", code: "FM", flag: "https://flagcdn.com/w320/fm.png" },
  { name: "Moldova", code: "MD", flag: "https://flagcdn.com/w320/md.png" },
  { name: "Monaco", code: "MC", flag: "https://flagcdn.com/w320/mc.png" },
  { name: "Mongolia", code: "MN", flag: "https://flagcdn.com/w320/mn.png" },
  { name: "Montenegro", code: "ME", flag: "https://flagcdn.com/w320/me.png" },
  { name: "Morocco", code: "MA", flag: "https://flagcdn.com/w320/ma.png" },
  { name: "Mozambique", code: "MZ", flag: "https://flagcdn.com/w320/mz.png" },
  {
    name: "Myanmar (Burma)",
    code: "MM",
    flag: "https://flagcdn.com/w320/mm.png",
  },
  { name: "Namibia", code: "NA", flag: "https://flagcdn.com/w320/na.png" },
  { name: "Nauru", code: "NR", flag: "https://flagcdn.com/w320/nr.png" },
  { name: "Nepal", code: "NP", flag: "https://flagcdn.com/w320/np.png" },
  { name: "Netherlands", code: "NL", flag: "https://flagcdn.com/w320/nl.png" },
  { name: "New Zealand", code: "NZ", flag: "https://flagcdn.com/w320/nz.png" },
  { name: "Nicaragua", code: "NI", flag: "https://flagcdn.com/w320/ni.png" },
  { name: "Niger", code: "NE", flag: "https://flagcdn.com/w320/ne.png" },
  {
    name: "North Macedonia",
    code: "MK",
    flag: "https://flagcdn.com/w320/mk.png",
  },
  { name: "Norway", code: "NO", flag: "https://flagcdn.com/w320/no.png" },
  { name: "Oman", code: "OM", flag: "https://flagcdn.com/w320/om.png" },
  { name: "Pakistan", code: "PK", flag: "https://flagcdn.com/w320/pk.png" },
  { name: "Palau", code: "PW", flag: "https://flagcdn.com/w320/pw.png" },
  {
    name: "Palestine State",
    code: "PS",
    flag: "https://flagcdn.com/w320/ps.png",
  },
  { name: "Panama", code: "PA", flag: "https://flagcdn.com/w320/pa.png" },
  {
    name: "Papua New Guinea",
    code: "PG",
    flag: "https://flagcdn.com/w320/pg.png",
  },
  { name: "Paraguay", code: "PY", flag: "https://flagcdn.com/w320/py.png" },
  { name: "Peru", code: "PE", flag: "https://flagcdn.com/w320/pe.png" },
  { name: "Philippines", code: "PH", flag: "https://flagcdn.com/w320/ph.png" },
  { name: "Poland", code: "PL", flag: "https://flagcdn.com/w320/pl.png" },
  { name: "Portugal", code: "PT", flag: "https://flagcdn.com/w320/pt.png" },
  { name: "Qatar", code: "QA", flag: "https://flagcdn.com/w320/qa.png" },
  { name: "Romania", code: "RO", flag: "https://flagcdn.com/w320/ro.png" },
  { name: "Russia", code: "RU", flag: "https://flagcdn.com/w320/ru.png" },
  { name: "Rwanda", code: "RW", flag: "https://flagcdn.com/w320/rw.png" },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    flag: "https://flagcdn.com/w320/kn.png",
  },
  { name: "Saint Lucia", code: "LC", flag: "https://flagcdn.com/w320/lc.png" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    flag: "https://flagcdn.com/w320/vc.png",
  },
  { name: "Samoa", code: "WS", flag: "https://flagcdn.com/w320/ws.png" },
  { name: "San Marino", code: "SM", flag: "https://flagcdn.com/w320/sm.png" },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    flag: "https://flagcdn.com/w320/st.png",
  },
  { name: "Saudi Arabia", code: "SA", flag: "https://flagcdn.com/w320/sa.png" },
  { name: "Senegal", code: "SN", flag: "https://flagcdn.com/w320/sn.png" },
  { name: "Serbia", code: "RS", flag: "https://flagcdn.com/w320/rs.png" },
  { name: "Seychelles", code: "SC", flag: "https://flagcdn.com/w320/sc.png" },
  { name: "Sierra Leone", code: "SL", flag: "https://flagcdn.com/w320/sl.png" },
  { name: "Singapore", code: "SG", flag: "https://flagcdn.com/w320/sg.png" },
  { name: "Slovakia", code: "SK", flag: "https://flagcdn.com/w320/sk.png" },
  { name: "Slovenia", code: "SI", flag: "https://flagcdn.com/w320/si.png" },
  {
    name: "Solomon Islands",
    code: "SB",
    flag: "https://flagcdn.com/w320/sb.png",
  },
  { name: "Somalia", code: "SO", flag: "https://flagcdn.com/w320/so.png" },
  { name: "South Africa", code: "ZA", flag: "https://flagcdn.com/w320/za.png" },
  { name: "South Sudan", code: "SS", flag: "https://flagcdn.com/w320/ss.png" },
  { name: "Spain", code: "ES", flag: "https://flagcdn.com/w320/es.png" },
  { name: "Sri Lanka", code: "LK", flag: "https://flagcdn.com/w320/lk.png" },
  { name: "Sudan", code: "SD", flag: "https://flagcdn.com/w320/sd.png" },
  { name: "Suriname", code: "SR", flag: "https://flagcdn.com/w320/sr.png" },
  { name: "Sweden", code: "SE", flag: "https://flagcdn.com/w320/se.png" },
  { name: "Switzerland", code: "CH", flag: "https://flagcdn.com/w320/ch.png" },
  { name: "Syria", code: "SY", flag: "https://flagcdn.com/w320/sy.png" },
  { name: "Tajikistan", code: "TJ", flag: "https://flagcdn.com/w320/tj.png" },
  { name: "Tanzania", code: "TZ", flag: "https://flagcdn.com/w320/tz.png" },
  { name: "Thailand", code: "TH", flag: "https://flagcdn.com/w320/th.png" },
  { name: "Timor-Leste", code: "TL", flag: "https://flagcdn.com/w320/tl.png" },
  { name: "Togo", code: "TG", flag: "https://flagcdn.com/w320/tg.png" },
  { name: "Tonga", code: "TO", flag: "https://flagcdn.com/w320/to.png" },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    flag: "https://flagcdn.com/w320/tt.png",
  },
  { name: "Tunisia", code: "TN", flag: "https://flagcdn.com/w320/tn.png" },
  { name: "Turkey", code: "TR", flag: "https://flagcdn.com/w320/tr.png" },
  { name: "Turkmenistan", code: "TM", flag: "https://flagcdn.com/w320/tm.png" },
  { name: "Tuvalu", code: "TV", flag: "https://flagcdn.com/w320/tv.png" },
  { name: "Uganda", code: "UG", flag: "https://flagcdn.com/w320/ug.png" },
  { name: "Ukraine", code: "UA", flag: "https://flagcdn.com/w320/ua.png" },
  {
    name: "United Arab Emirates",
    code: "AE",
    flag: "https://flagcdn.com/w320/ae.png",
  },
  {
    name: "United Kingdom",
    code: "GB",
    flag: "https://flagcdn.com/w320/gb.png",
  },

  { name: "Uruguay", code: "UY", flag: "https://flagcdn.com/w320/uy.png" },
  { name: "Uzbekistan", code: "UZ", flag: "https://flagcdn.com/w320/uz.png" },
  { name: "Vanuatu", code: "VU", flag: "https://flagcdn.com/w320/vu.png" },
  { name: "Vatican City", code: "VA", flag: "https://flagcdn.com/w320/va.png" },
  { name: "Venezuela", code: "VE", flag: "https://flagcdn.com/w320/ve.png" },
  { name: "Vietnam", code: "VN", flag: "https://flagcdn.com/w320/vn.png" },
  { name: "Yemen", code: "YE", flag: "https://flagcdn.com/w320/ye.png" },
  { name: "Zambia", code: "ZM", flag: "https://flagcdn.com/w320/zm.png" },
  { name: "Zimbabwe", code: "ZW", flag: "https://flagcdn.com/w320/zw.png" },
];

export default countries;
